create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,email text not null,role text not null default 'user' check (role in ('user','admin')),created_at timestamptz not null default now());
create table if not exists public.subscriptions (user_id uuid primary key references public.profiles(id) on delete cascade,plan text not null default 'free' check (plan in ('free','pro')),status text not null default 'active',expires_at timestamptz,updated_at timestamptz not null default now());
create table if not exists public.payments (id bigint generated by default as identity primary key,user_id uuid not null references public.profiles(id) on delete cascade,email text,order_id text unique not null,bill_code text,amount_sen integer not null default 0,status text not null default 'created',refno text,raw jsonb,created_at timestamptz not null default now(),paid_at timestamptz);
alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.payments enable row level security;
-- Backend uses SUPABASE_SERVICE_ROLE_KEY. Never expose it in frontend JavaScript.
